name        : alsa-utils
version     : 1.0.27.2
release     : 5
source      :
    - ftp://ftp.alsa-project.org/pub/utils/alsa-utils-1.0.27.2.tar.bz2 : 02bfac39092f3b68d743c23ad3d688d6c5aa8df69f2ccd692c5b8282edb352ea
homepage    : http://www.alsa-project.org
license     : GPL-2.0
summary     : Various utilities which are useful for controlling your sound card
builddeps   :
    - pkgconfig(alsa)
description : |
    Various utilities which are useful for controlling your sound card
setup      : |
    %configure --disable-alsaconf \
               --disable-xmlto \
               --with-udev-rules-dir=/usr/lib/udev/rules.d
build      : |
    %make
install    : |
    %make_install
