name       : alsa-utils
version    : 1.2.1
release    : 14
source     :
    - ftp://ftp.alsa-project.org/pub/utils/alsa-utils-1.2.1.tar.bz2 : 0b110ba71ef41d3009db1bc4dcae0cf79efb99cb5426fa19d0312470560a2c0d
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Various utilities which are useful for controlling your sound card
description: |
    Various utilities which are useful for controlling your sound card
builddeps  :
    - pkgconfig(alsa)
setup      : |
    %configure --disable-alsaconf \
               --disable-xmlto \
               --with-udev-rules-dir=/usr/lib/udev/rules.d
build      : |
    %make
install    : |
    %make_install
    rmdir $installdir/usr/share/man/man7
