name       : alsa-utils
version    : 1.2.2
release    : 15
source     :
    - ftp://ftp.alsa-project.org/pub/utils/alsa-utils-1.2.2.tar.bz2 : 44807bd578c5f6df6e91a11b8d37e546424a5a1ea8d8e659ee359fe01730e4f3
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Various utilities which are useful for controlling your sound card
description: |
    Various utilities which are useful for controlling your sound card
builddeps  :
    - pkgconfig(alsa)
setup      : |
    %configure --disable-alsaconf \
               --disable-xmlto \
               --with-udev-rules-dir=/usr/lib/udev/rules.d
build      : |
    %make
install    : |
    %make_install
    rmdir $installdir/usr/share/man/man7
