name        : alsa-utils
version     : 1.1.1
release     : 7
source     :
    - ftp://ftp.alsa-project.org/pub/utils/alsa-utils-1.1.1.tar.bz2 : 89757c9abaf420831b088fce354d492acc170bd02bb50eb7392c175f594b8041
license     : GPL-2.0
summary     : Various utilities which are useful for controlling your sound card
builddeps   :
    - pkgconfig(alsa)
description : |
    Various utilities which are useful for controlling your sound card
setup      : |
    %configure --disable-alsaconf \
               --disable-xmlto \
               --with-udev-rules-dir=/usr/lib/udev/rules.d
build      : |
    %make
install    : |
    %make_install
